name: Metrics
on:
  # Schedule updates (daily)
  schedule: [{ cron: "0 0 * * *" }]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push:
      branches: ["master", "main"]
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    
      - name: Achievements
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: achievements.svg
          token: ${{ secrets.METRICS_SECRET }}
          base: ""
          output_action: gist
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C

      - name: Calendar
        uses: lowlighter/metrics@latest
        with:
          filename: static/images/calendar.svg
          token: ${{ secrets.METRICS_SECRET }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

      - name: Indepth analysis
        uses: lowlighter/metrics@latest
        with:
          filename: static/images/languages.svg
          token: ${{ secrets.METRICS_SECRET }}
          base: ""
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_details: lines, bytes-size
          plugin_languages_limit: 4
          plugin_languages_analysis_timeout: 15
